### ISSUE TITLE
Dupla atribuição

### ISSUE THREAD

**Issue by la-costa** [MarceloWalther-Dev/faculdadeJogo#1]
Oi Marcelo,

Nessa linha você altera o atributo pontuacao e depois seta ele novamente, ou seja, está fazendo a mudança duas vezes, desnecessariamente.

https://github.com/MarceloWalther-Dev/faculdadeJogo/blob/137aa1f1682303b08c43cfc350a9ee45877c8282/Jogo/src/pedraPapelTesoura/Jogador1.java#L31-L32

**Comment by MarceloWalther-Dev** [comment]
Então a parte que comentei sobre gambiarra, hoje estarei trabalhando em cima do projeto novamente, obrigado pela dica.
